CREATE TABLE SERVICE_USER(
  NAME VARCHAR(50) PRIMARY KEY
);

CREATE TABLE ACCESS_KEY(
  KEY VARCHAR(100) PRIMARY KEY,
  VALID_TO TIMESTAMP,
  USER_NAME VARCHAR(50) REFERENCES SERVICE_USER(NAME)
);

CREATE TABLE INGRESS_TYPES(
  TYPE VARCHAR(20) PRIMARY KEY
);

CREATE TABLE INGRESS_RESOURCE(
  NAME VARCHAR(250) PRIMARY KEY,
  HOST VARCHAR(250) DEFAULT 'localhost',
  PORT INTEGER,
  IMAGE VARCHAR(250),
  HEALTH_ROUTE VARCHAR(250) DEFAULT '/health',
  ROLE VARCHAR(20) REFERENCES INGRESS_TYPES(TYPE)
);

CREATE TABLE SERVICE(
  NAME VARCHAR(250) PRIMARY KEY,
  PORT INTEGER,
  DOMAIN VARCHAR(250),
  IMAGE VARCHAR(250),
  VOLUME_MOUNT VARCHAR(250),
  DATE_CHANGED TIMESTAMP,
  ACTIVE BOOLEAN,
  USER_NAME VARCHAR(50) REFERENCES SERVICE_USER(NAME)
);

CREATE TABLE ENV(
  NAME VARCHAR(250),
  VALUE TEXT,
  SERVICE VARCHAR(250) REFERENCES SERVICE(NAME),
  PRIMARY KEY(SERVICE, NAME)
);

CREATE TABLE AGENT_METADATA(
  AGENT_ID VARCHAR(64),
  LAST_UPDATED TIMESTAMP
);

INSERT INTO INGRESS_TYPES(TYPE) VALUES ('PROXY'), ('LOADBALANCER');
